parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[Twitter-Piko]
app-name = "Twitter"
rv-brand = "Piko"
patches-source = "crimera/piko"
cli-source = "MorpheApp/morphe-cli"
patches-version = "dev"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter"
uptodown-dlurl = "https://twitter.en.uptodown.com/android"
build-mode = "apk"
included-patches = "'Bring back twitter' 'Change version code'"

[Twitter-Piko-Material-You]
app-name = "Twitter"
rv-brand = "Piko-Material-You"
patches-source = "crimera/piko"
cli-source = "MorpheApp/morphe-cli"
patches-version = "dev"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter"
uptodown-dlurl = "https://twitter.en.uptodown.com/android"
build-mode = "apk"
included-patches = "'Bring back twitter' 'Change version code' 'Dynamic color'"
